### ISSUE TITLE
Empty pictures with no srcsets

### ISSUE THREAD

**Issue by dominicwa** [oleeskild/digitalgarden#142]
I just setup a new digital garden on Vercel, following the Getting Started process. Everything went pretty smoothly. Awesome plugin / docs - thanks.

One thing though... I noticed locally embedded images weren't showing up. I just got an empty ```<picture src="path/to/image"></picture>``` with no srcset in the middle. Which showed nothing in Safari.

If I go into the DOM and change the picture to a plain ```<img src="path/to/image"/>``` it works fine. So the original image upload and path are all ok.

Under further investigation I've found if I comment out [L314](https://github.com/oleeskild/digitalgarden/blob/4b93ad4e43e25ad460ecc08f8b99443b3382bcf2/.eleventy.js#L314) to [L362](https://github.com/oleeskild/digitalgarden/blob/4b93ad4e43e25ad460ecc08f8b99443b3382bcf2/.eleventy.js#L362) in  [.eleventy.js](https://github.com/oleeskild/digitalgarden/blob/main/.eleventy.js), then everything works ok again.

I think this relates to the recent [Image optimization](https://github.com/oleeskild/digitalgarden/pull/116) PR that was merged in.

I haven't pinned down the exact problem I'm afraid but maybe it'll be obvious to someone else... I think the transformImage() call in the try is failing (and the catch is currently empty so probably not indicating much other than someone should "// Make it fault tolarent." 😉).

**Comment by bayang** [comment]
I experienced the exact same issue.
The problem is where @dominicwa  pointed out.
Actually, lines 343 and 348, if meta.webp[1] and meta.jpeg[1] do not exist, an exception is thrown and no  html is generated.
This is why we end up with empty srcset on the picture element.

The root cause is that if your source image is small, the 11ty-image plugin will not do anything and you will end up with only 1 element in the metadata result.
Like this : 
```
metadata  
{  
webp: [  
{  
format: 'webp',  
width: 64,  
height: 89,  
url: '/img/optimized/HAiNBOCmsI-64.webp',  
sourceType: 'image/webp',  
srcset: '/img/optimized/HAiNBOCmsI-64.webp 64w',  
filename: 'HAiNBOCmsI-64.webp',  
outputPath: 'dist/img/optimized/HAiNBOCmsI-64.webp'  
}  
],  
jpeg: [  
{  
format: 'jpeg',  
width: 64,  
height: 89,  
url: '/img/optimized/HAiNBOCmsI-64.jpeg',  
sourceType: 'image/jpeg',  
srcset: '/img/optimized/HAiNBOCmsI-64.jpeg 64w',  
filename: 'HAiNBOCmsI-64.jpeg',  
outputPath: 'dist/img/optimized/HAiNBOCmsI-64.jpeg'  
}  
]  
}  
TypeError: Cannot read properties of undefined (reading 'url')  
at Object.<anonymous> (/home/bg/garden/.eleventy.js:357:30)  
at Object.<anonymous> (/home/bg/garden/node_modules/@11ty/eleventy/src/BenchmarkGroup.js:32:26)  
at Template.runTransforms (/home/bg/garden/node_modules/@11ty/eleventy/src/Template.js:514:30)  
at processTicksAndRejections (node:internal/process/task_queues:96:5)  
at async Template.renderPageEntry (/home/bg/garden/node_modules/@11ty/eleventy/src/Template.js:799:15)  
at async /home/bg/garden/node_modules/@11ty/eleventy/src/Template.js:822:21  
at async Promise.all (index 0)  
at async Promise.all (index 1)  
at async Eleventy.executeBuild (/home/bg/garden/node_modules/@11ty/eleventy/src/Eleventy.js:1191:13)  
at async Eleventy._watch (/home/bg/garden/node_modules/@11ty/eleventy/src/Eleventy.js:822:24)
```
I got the stacktrace above by logging the error in the catch statement (actually, silently swallowing exceptions was not very useful, and not fault tolerant either since we end up with wrong html anyway ;) ).

I'll submit a PR if possible.
I tested locally with small and bigger pictures : the fix seems to work.

**Comment by bayang** [comment]
Actually, I just remembered I made my repo private when I created my garden so I can't submit a PR.
So here's a patch instead (the fix is small anyway).

[0001-fix-prevent-out-of-bonds-access-which-leads-to-empty.txt](https://github.com/oleeskild/digitalgarden/files/11359684/0001-fix-prevent-out-of-bonds-access-which-leads-to-empty.txt)

**Comment by oleeskild** [comment]
Great, thank you for providing a fix! I've added it to the latest version of the template.
