### ISSUE TITLE
Is "@azure/storage-blob": "^12.8.0" in use anywhere

### ISSUE THREAD

**Issue by anantshri** [oleeskild/digitalgarden#158]
been exploring the code a bit and understanding what and where is in use. I realized there is no reference in code anywhere for azure/storage-blob except in package.json and package-lock.json.

1. Are we using this npm module anywhere at all.

I ran `npx npm-check` that helped me find this. it also find sass but then i can see it being used as a binary in build steps so it makes sens but stuck with finding usage for storage-blob

**Comment by oleeskild** [comment]
You are correct, it is not in use. The first iteration of this plugin used azure blob storage instead of github for storing the documents. I've just forgotten to remove it. 
I'll try to look through all the PRs for the plugin and template this week, and create a new release. I'll also remove the reference to this package in the process. Thanks for letting me know about it!

**Comment by anantshri** [comment]
awesome. I have been messing around with the code mostly around dependency reduction or upgrade. (dont ask i am a glutton for punishment) https://github.com/anantshri/digitalgarden is the repo where you can see those changes.
