### ISSUE TITLE
Transclusions render metadata under title

### ISSUE THREAD

**Issue by ThatOtherAndrew** [oleeskild/digitalgarden#3]
### Problem
Since the transclusion has an inserted `h1` title at the top, the metadata is inserted below, and is rendered in the resultant note.

### Proposed Solution
Strip away the metadata before inserting it into the transclusion. Customisation over how/whether the title is rendered as a heading would also be helpful as an added bonus.

### Attachments
![image](https://user-images.githubusercontent.com/26030336/157756730-7050582a-0d24-4c99-bb07-728fdd9f1fe9.png)
![image](https://user-images.githubusercontent.com/26030336/157757096-8885395a-5d2c-405d-82d0-37d13218823d.png)

---
(Sorry that I'm launching issues at you like hot potatoes - this is a brilliant tool, and please let me know if I'm being overly feature-hungry!)

**Comment by oleeskild** [comment]
No, this is great. It helps to find use-cases and bugs I would not have noticed myself. Keep them coming!

I've published a new version of the plugin which removed the frontmatter from transclusions.

Regarding the setting on rendering the file title or not, I wanted to implement it so that it could be decided per transclusion by the document that does the transcluding so that it can be custom for each transclusion. I've solved it by allowing you to use the pipe character to set the title. There are more info about it in the latest version of the README.md. Let me know if this solution works for you.

**Comment by ThatOtherAndrew** [comment]
The pipe character is a very elegant solution, thank you! However, one further request; could there be a way to override the heading size please? An `h1` element can look too big in the middle of a note, and solutions involving injecting HTML after the pipe are quite messy.

**Comment by oleeskild** [comment]
Agreed, that would be helpful. I've released a new version which lets you specify heading level like so:
![[Some note|##My header]]

This will result in a h2.

If you don't add any #s in front of the title, it defaults to h1.

**Comment by ThatOtherAndrew** [comment]
That's absolutely perfect, thank you!
